USE AccountOMS
GO
DROP TABLE dbo.t_Case_UnitCode_V006
go
CREATE TABLE t_Case_UnitCode_V006
(
	DateInsert DATETIME NOT NULL DEFAULT(GETDATE()),
	rf_idCase BIGINT NOT NULL,
	UnitCode SMALLINT NOT NULL,
	V006 TINYINT NOT NULL
) ON AccountMU
GO

CREATE UNIQUE NONCLUSTERED INDEX IX_IdCase ON dbo.t_Case_UnitCode_V006(rf_idCase, UnitCode) INCLUDE(V006) WITH IGNORE_DUP_KEY