USE RegisterCases
go
SET NOCOUNT ON

CREATE NONCLUSTERED INDEX IX_Meduslugi_AccountOMS ON dbo.t_Meduslugi(rf_idCase)
INCLUDE(id,GUID_MU,rf_idMO,rf_idV002,IsChildTariff,DateHelpBegin,DateHelpEnd,DiagnosisCode,
		MUCode,Quantity,Price,TotalPrice,rf_idV004) 
WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = ON, IGNORE_DUP_KEY = OFF, 
					DROP_EXISTING = OFF, ONLINE = ON, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON)
GO
CREATE NONCLUSTERED INDEX IX_MES_AccountOMS ON [dbo].[t_MES] ([MES]) INCLUDE ([rf_idCase]) 
WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = ON, IGNORE_DUP_KEY = OFF,
		 DROP_EXISTING = OFF, ONLINE = ON, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON)
GO
--USE AccountOMS
--SELECT * FROM vw_sprMuWithParamAccount