USE AccountOMS
GO
DECLARE @dateStartReg DATETIME='20200101',
		@dateEndReg DATETIME=GETDATE(),
		@dateStartRegRAK DATETIME='20200101',
		@dateEndRegRAK DATETIME=GETDATE(),
		@reportYear SMALLINT=2020
		

SELECT a.rf_idSMO,cc.AmountPayment,c.rf_idV006,a.id,a.Letter,cc.id AS rf_idCompletedCase
INTO #tCase
FROM dbo.t_File f INNER JOIN dbo.t_RegistersAccounts a ON
			f.id=a.rf_idFiles
					INNER JOIN dbo.t_RecordCasePatient r ON
			a.id=r.rf_idRegistersAccounts
					INNER JOIN dbo.t_PatientSMO p ON
            r.id=p.rf_idRecordCasePatient			
					INNER JOIN dbo.t_Case c ON
			r.id=c.rf_idRecordCasePatient								
					INNER JOIN dbo.t_CompletedCase cc ON
			r.id=cc.rf_idRecordCasePatient								
WHERE f.DateRegistration>=@dateStartReg AND f.DateRegistration<@dateEndReg  AND a.ReportYear=@reportYear 


SELECT 'Стационар'
	,COUNT(DISTINCT CASE WHEN rf_idSMO='34002' THEN id ELSE NULL END) AS Account34002
	,COUNT(DISTINCT CASE WHEN rf_idSMO='34002' THEN rf_idCompletedCase ELSE NULL END) AS Case34002
	,COUNT(DISTINCT CASE WHEN rf_idSMO='34007' THEN id ELSE NULL END) AS Account34007
	,COUNT(DISTINCT CASE WHEN rf_idSMO='34007' THEN rf_idCompletedCase ELSE NULL END) AS Case34007
	,COUNT(DISTINCT CASE WHEN rf_idSMO='34' THEN id ELSE NULL END) AS Account34
	,COUNT(DISTINCT CASE WHEN rf_idSMO='34' THEN rf_idCompletedCase ELSE NULL END) AS Case34
FROM #tCase
WHERE rf_idV006=1 AND Letter='S'
UNION ALL
SELECT 'ВМП'
	,COUNT(DISTINCT CASE WHEN rf_idSMO='34002' THEN id ELSE NULL END) AS Account34002
	,COUNT(DISTINCT CASE WHEN rf_idSMO='34002' THEN rf_idCompletedCase ELSE NULL END) AS Case34002
	,COUNT(DISTINCT CASE WHEN rf_idSMO='34007' THEN id ELSE NULL END) AS Account34007
	,COUNT(DISTINCT CASE WHEN rf_idSMO='34007' THEN rf_idCompletedCase ELSE NULL END) AS Case34007
	,COUNT(DISTINCT CASE WHEN rf_idSMO='34' THEN id ELSE NULL END) AS Account34
	,COUNT(DISTINCT CASE WHEN rf_idSMO='34' THEN rf_idCompletedCase ELSE NULL END) AS Case34
FROM #tCase
WHERE rf_idV006=1 AND Letter='H'
UNION ALL
SELECT 'Дневной стационар'
	,COUNT(DISTINCT CASE WHEN rf_idSMO='34002' THEN id ELSE NULL END) AS Account34002
	,COUNT(DISTINCT CASE WHEN rf_idSMO='34002' THEN rf_idCompletedCase ELSE NULL END) AS Case34002
	,COUNT(DISTINCT CASE WHEN rf_idSMO='34007' THEN id ELSE NULL END) AS Account34007
	,COUNT(DISTINCT CASE WHEN rf_idSMO='34007' THEN rf_idCompletedCase ELSE NULL END) AS Case34007
	,COUNT(DISTINCT CASE WHEN rf_idSMO='34' THEN id ELSE NULL END) AS Account34
	,COUNT(DISTINCT CASE WHEN rf_idSMO='34' THEN rf_idCompletedCase ELSE NULL END) AS Case34
FROM #tCase
WHERE rf_idV006=2
UNION ALL
SELECT 'АПП'
	,COUNT(DISTINCT CASE WHEN rf_idSMO='34002' THEN id ELSE NULL END) AS Account34002
	,COUNT(DISTINCT CASE WHEN rf_idSMO='34002' THEN rf_idCompletedCase ELSE NULL END) AS Case34002
	,COUNT(DISTINCT CASE WHEN rf_idSMO='34007' THEN id ELSE NULL END) AS Account34007
	,COUNT(DISTINCT CASE WHEN rf_idSMO='34007' THEN rf_idCompletedCase ELSE NULL END) AS Case34007
	,COUNT(DISTINCT CASE WHEN rf_idSMO='34' THEN id ELSE NULL END) AS Account34
	,COUNT(DISTINCT CASE WHEN rf_idSMO='34' THEN rf_idCompletedCase ELSE NULL END) AS Case34
FROM #tCase
WHERE rf_idV006=3
UNION ALL
SELECT 'СМП'
	,COUNT(DISTINCT CASE WHEN rf_idSMO='34002' THEN id ELSE NULL END) AS Account34002
	,COUNT(DISTINCT CASE WHEN rf_idSMO='34002' THEN rf_idCompletedCase ELSE NULL END) AS Case34002
	,COUNT(DISTINCT CASE WHEN rf_idSMO='34007' THEN id ELSE NULL END) AS Account34007
	,COUNT(DISTINCT CASE WHEN rf_idSMO='34007' THEN rf_idCompletedCase ELSE NULL END) AS Case34007
	,COUNT(DISTINCT CASE WHEN rf_idSMO='34' THEN id ELSE NULL END) AS Account34
	,COUNT(DISTINCT CASE WHEN rf_idSMO='34' THEN rf_idCompletedCase ELSE NULL END) AS Case34
FROM #tCase
WHERE rf_idV006=4
GO
DROP TABLE #tCase