USE AccountOMS
GO
/*
SELECT *
FROM dbo.t_260order_ONK WHERE IsUnload IS NULL AND MONTH=2

SELECT * FROM dbo.t_260order_ONK WHERE IsUnload IS NULL AND MONTH=2 AND GUID_Case='EEB121D6-4DDD-0E16-7D53-53523CD2C5CC'
SELECT * FROM dbo.t_260order_ONK WHERE IsUnload IS NULL AND MONTH=2 AND id_pac='F2456373-8CDC-A746-AE53-23CD2C5C9FD7'

BEGIN TRANSACTION
SELECT * INTO tmp_260order_onk_20210312 FROM dbo.t_260order_ONK WHERE IsUnload=1 AND MONTH=2
DELETE FROM dbo.t_260order_ONK WHERE IsUnload=1 AND MONTH=2
COMMIT
*/
BEGIN TRANSACTION
INSERT dbo.t_260order_ONK(id,VERSION,DATA,FILENAME,CODE,CODE_MO,YEAR,MONTH,Account,DateRegister,PLAT,SUMMAV,rf_idRecordCasePatient,N_ZAP,IsNew,ID_PAC,VPOLIS,SPOLIS,NPOLIS,ST_OKATO,
						rf_idSMO,SMO_OGRN,SMO_OK,SMO_NAM,MSE,NOVOR,BirthWeight,IDCASE,USL_OK,VIDPOM,FOR_POM,NPR_MO,LPU,DATE_Z_1,Date_Z_2,KD_Z,RSLT,ISHOD,IDSP,AmountPayment,rf_idCase,
						GUID_Case,VID_HMP,METOD_HMP,LPU_1,PODR,rf_idV002,PROFIL_K,DET,TAL_D,TAL_NUM,TAL_P,NHISTORY,DATE_1,DATE_2,DS1,C_ZAB,DS_ONK,PRVS,VERS_SPEC,IDDOKT,Quantity,Tariff,
						SUM_M,CodeSMO34,IsUnload)
SELECT id,VERSION,DATA,FILENAME,CODE,CODE_MO,YEAR,MONTH,Account,DateRegister,PLAT,SUMMAV,rf_idRecordCasePatient,N_ZAP,IsNew,ID_PAC,VPOLIS,SPOLIS,NPOLIS,ST_OKATO,
						rf_idSMO,SMO_OGRN,SMO_OK,SMO_NAM,MSE,NOVOR,BirthWeight,IDCASE,USL_OK,VIDPOM,FOR_POM,NPR_MO,LPU,DATE_Z_1,Date_Z_2,KD_Z,RSLT,ISHOD,IDSP,AmountPayment,rf_idCase,
						GUID_Case,VID_HMP,METOD_HMP,LPU_1,PODR,rf_idV002,PROFIL_K,DET,TAL_D,TAL_NUM,TAL_P,NHISTORY,DATE_1,DATE_2,DS1,C_ZAB,DS_ONK,PRVS,VERS_SPEC,IDDOKT,Quantity,Tariff,
						SUM_M,CodeSMO34,1
 FROM tmp_260order_onk_20210312 
 COMMIT
 go
 DROP TABLE tmp_260order_onk_20210312