USE RegisterCases
GO
declare @p1 XML,
		@idoc int

SELECT	@p1=HRM.ZL_LIST				
FROM	OPENROWSET(BULK 'c:\Test\CT34_19014.xml',SINGLE_BLOB) HRM (ZL_LIST)

EXEC sp_xml_preparedocument @idoc OUTPUT, @p1

SELECT *
INTO #t
FROM OPENXML (@idoc, 'ZL_LIST/SCHET/ZAP/Z_SL/SL/KSG_KPG',2)
	WITH(
			SL_ID UNIQUEIDENTIFIER '../SL_ID',
			USL_OK TINYINT '../../USL_OK',
			N_KSG NVARCHAR(10)

		)

SELECT *
INTO #t1
FROM OPENXML (@idoc, 'ZL_LIST/SCHET/ZAP/Z_SL/SL',2)
	WITH(
			SL_ID UNIQUEIDENTIFIER ,
			USL_OK TINYINT '../USL_OK'
		)
WHERE USL_OK<3

SELECT *
FROM #t1 t WHERE NOT EXISTS(SELECT 1 FROM #t tt WHERE tt.SL_ID=t.SL_ID)

EXEC sp_xml_removedocument @idoc
GO
DROP TABLE #t
DROP TABLE #t1